sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dotway/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dotway/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-330154092120"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"